name: Build 👷

on:
  push:
    branches-ignore: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deployment:
    strategy:
      matrix:
        target: [base, gcp]
        platform: [linux/amd64, linux/arm64]
    name: Build the image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bake the ${{ matrix.target }} image
        uses: docker/bake-action@v6
        with:
          targets: ${{ matrix.target }}
          load: true
          push: false
          set: |
            ${{ matrix.target }}.tags=alpine-fips:${{ matrix.target }}-${{ github.sha }}
            ${{ matrix.target }}.platform=${{ matrix.platform }}
