name: Publish 🚀

on:
  schedule:
    - cron: '0 5,19 * * *'
  workflow_dispatch:

jobs:
  deployment:
    name: Publish the image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      OPENSSL_VERSION: "3.0.9"
      OPENSSL_HASH: "eb1ab04781474360f77c318ab89d8c5a03abc38e63d65a603cabbf1b00a1dc90"
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Check if tag exists already
        id: check_tag
        run: |
          if git rev-parse ${{ env.OPENSSL_VERSION }} >/dev/null 2>&1
          then
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set image name as env var
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ env.OPENSSL_VERSION }}" >> $GITHUB_ENV
          echo "IMAGE_NAME_LATEST=ghcr.io/${{ github.repository }}:latest" >> $GITHUB_ENV

      - name: Set up QEMU
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Log in to GitHub registry
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        if: steps.check_tag.outputs.tag_exists == 'false'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build the image
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            OPENSSL_VERSION=${{ env.OPENSSL_VERSION }}
            OPENSSL_HASH=${{ env.OPENSSL_HASH }}
          tags: |
            ${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME_LATEST }}

      - name: Push tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git config --local user.email "cicd@spacelift.io"
          git config --local user.name "Spacelift CI/CD"
          git tag -a ${{ env.OPENSSL_VERSION }} -m "OpenSSL v${{ env.OPENSSL_VERSION }}"
          git push origin ${{ env.OPENSSL_VERSION }}

      - name: Create release
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.OPENSSL_VERSION }}
          tag: ${{ env.OPENSSL_VERSION }}
          makeLatest: true
          skipIfReleaseExists: true
          body: |
            Release of OpenSSL FIPS ${{ env.OPENSSL_VERSION }}.

            To use it in your Dockerfile, add the following lines:
            ```dockerfile
            FROM ${{ env.IMAGE_NAME }}
            ```